
services:
  # Backend
  backend:
    build: ./backend
    image: yolo-backend:v2.0.0
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
     - app-mongo
    env_file:
      - ./backend/.env
    networks:
      - back-network
      - client-network
  
  #database
  app-mongo:
    image: mongo:6.0
    container_name: my-mongo
    ports:
     - "8000:27017"
    networks:
     - back-network

  # Frontend
  client:
    build: ./client
    image: yolo-frontend:v1.0.0
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - client-network
      

networks:
  back-network:
   driver: bridge
  client-network:
    driver: bridge