
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
    - port: 27017
  clusterIP: None        
  selector:
    app: mongo-v2

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-v2
spec:
  serviceName: "mongo-service"
  replicas: 2
  selector:
    matchLabels:
      app: mongo-v2
  template:
    metadata:
      labels:
        app: mongo-v2
    spec:
      containers:
      - name: my-mongo
        image: joanodhiambo/mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: db-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
